### ISSUE TITLE
Temperature Celsius 

### ISSUE THREAD

**Issue by tight13** [sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library#1]
Hello,
when reading the Temperature Celsius i just get integer numbers
example: first 22.0°, then 23.0°
no steps between it.

**Comment by tight13** [comment]
Hello,
michael_x from arduino forum found the solution
int_32_t _temperature_actual = ...
 float temperature_reported = _temperature_actual / 100;
        return temperature_reported;

-> write / 100.0
then it its perfect for users who need celsius
source: http://forum.arduino.cc/index.php?topic=373268.0

**Comment by BrentWilkins** [comment]
Thanks for finding this. I removed the integer math that was truncating the value.
